project_id = "qrypwjkvpsatbvhtyeuw"

[functions.loader]
verify_jwt = false

[functions.validate-key]
verify_jwt = false

[functions.validate-key-v2]
verify_jwt = false

[functions.validate-key-v3]
verify_jwt = false

[functions.get-script]
verify_jwt = false

[functions.heartbeat]
verify_jwt = false

[functions.auth-handshake]
verify_jwt = false

[functions.ad-key-system]
verify_jwt = false

[functions.obfuscate-lua]
verify_jwt = false

[functions.obfuscate-script]
verify_jwt = false

[functions.discord-bot]
verify_jwt = false

[functions.discord-webhook]
verify_jwt = false

[functions.get-session-status]
verify_jwt = false

[functions.create-crypto-invoice]
verify_jwt = false

[functions.crypto-webhook]
verify_jwt = false

[functions.sync]
verify_jwt = false

[functions.auth-version]
verify_jwt = false

[functions.auth-info]
verify_jwt = false

[functions.auth-endpoints]
verify_jwt = false

[functions.auth-flags]
verify_jwt = false

[functions.external-key-check]
verify_jwt = false

[functions.wss-broker]
verify_jwt = false

[functions.binary-delivery]
verify_jwt = false

[functions.api-status]
verify_jwt = false

[functions.api-keys-manage]
verify_jwt = false

[functions.api-keys-resethwid]
verify_jwt = false

[functions.api-keys-blacklist]
verify_jwt = false

[functions.api-keys-unban]
verify_jwt = false

[functions.api-keys-linkdiscord]
verify_jwt = false
